security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory: { memory: ~ }
#        my_in_memory_provider:
#            memory:
#                users:
#                    foo:
#                        password:           foo
#                        roles:              [ROLE_USER, ROLE_ADMIN]
#                    bar:
#                        password:           bar
#                        roles:              [ROLE_USER, ROLE_ADMIN]

        my_entity_provider:
            entity:
                class:              App\Entity\User
                property:           username

    encoders:
            # Examples:
#            Symfony\Component\Security\Core\User\User: plaintext
            App\Entity\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
              login_path: login
              check_path: login
              default_target_path: home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: [ROLE_USER, ROLE_ADMIN] }


            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
